apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/chankyswami/*

  destinations:
    # Parent apps (App-of-Apps)
    - namespace: argocd
      server: https://kubernetes.default.svc

    # Workload apps
    - namespace: gfj-dev
      server: https://172.16.16.100:6443

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'