apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/chankyswami/*

  destinations:
    # Parent apps
    - namespace: argocd
      server: https://kubernetes.default.svc

    # Workload apps
    - namespace: gfj-prod
      server: https://172.16.16.100:6443

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

# Enable sync 
  syncWindows:
  - kind: allow
    applications:
      - gfj-frontend-prod

# Disable sync 
  # syncWindows: 
  #   - kind: deny
  #     applications:
  #       - "*"