apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gfj-frontend-prod
  namespace: argocd
spec:
  project: prod

  source:
    repoURL: https://github.com/chankyswami/gfj-frontend-deployment.git
    targetRevision: main
    path: helm/gfj-frontend
    helm:
      valueFiles:
        - values-prod.yaml

  destination:
    server: https://172.16.16.100:6443
    namespace: gfj-prod

  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true